version: 2
updates:
  - package-ecosystem: "gomod"
    directory: /s3secrets-helper
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 2
    reviewers:
      - "buildkite/agent-stewards"
