package env

const (
	EnvBucket     = "BUILDKITE_PLUGIN_S3_SECRETS_BUCKET"
	EnvRegion     = "BUILDKITE_PLUGIN_S3_SECRETS_REGION"
	EnvPrefix     = "BUILDKITE_PLUGIN_S3_SECRETS_BUCKET_PREFIX"
	EnvPipeline   = "BUILDKITE_PIPELINE_SLUG"
	EnvRepo       = "BUILDKITE_REPO"
	EnvCredHelper = "BUILDKITE_PLUGIN_S3_SECRETS_CREDHELPER"
)