version: '3.5'

services:
  agent:
    build:
      context: .
      dockerfile: Dockerfile-compile
    volumes:
      - ../:/work:cached
    working_dir: /work
    environment:
      - GOOS
      - GOARCH
  release:
    build:
      dockerfile: Dockerfile-release
      context: .
    volumes:
      - ../:/work:cached
