steps:
  - wait

  - label: ":linux: x86_64"
    plugins:
      docker-compose#v3.7.0:
        config: .buildkite/docker-compose.yml
        run: agent
        mount-buildkite-agent: true
    command: .buildkite/steps/build-binary.sh
    env:
      GOOS: linux
      GOARCH: amd64

  - label: ":linux: arm64"
    plugins:
      docker-compose#v3.7.0:
        config: .buildkite/docker-compose.yml
        run: agent
        mount-buildkite-agent: true
    command: .buildkite/steps/build-binary.sh
    env:
      GOOS: linux
      GOARCH: arm64

  - label: ":windows: x86_64"
    plugins:
      docker-compose#v3.7.0:
        config: .buildkite/docker-compose.yml
        run: agent
        mount-buildkite-agent: true
    command: .buildkite/steps/build-binary.sh
    env:
      GOOS: windows
      GOARCH: amd64

  # Requires golang 1.17 with support for windows/arm64
  # https://tip.golang.org/doc/go1.17
  # https://github.com/golang/go/issues/36439
  # - label: ":windows: arm64"
  #   plugins:
  #     docker-compose#v3.7.0:
  #       config: .buildkite/docker-compose.yml
  #       run: agent
  #       mount-buildkite-agent: true
  #   command: .buildkite/steps/build-binary.sh
  #   env:
  #     GOOS: windows
  #     GOARCH: arm64

  - label: ":mac: x86_64"
    plugins:
      docker-compose#v3.7.0:
        config: .buildkite/docker-compose.yml
        run: agent
        mount-buildkite-agent: true
    command: .buildkite/steps/build-binary.sh
    env:
      GOOS: darwin
      GOARCH: amd64

  - label: ":mac: arm64"
    plugins:
      docker-compose#v3.7.0:
        config: .buildkite/docker-compose.yml
        run: agent
        mount-buildkite-agent: true
    command: .buildkite/steps/build-binary.sh
    env:
      GOOS: darwin
      GOARCH: arm64

  - wait

  - label: ":bash: :hammer:"
    plugins:
      docker-compose#v2.2.0:
        run: tests

  - label: "㊙️ git-credentials test"
    command: .buildkite/test_credentials.sh

  - wait

  - block: ":git: tag?"
    prompt: "Tag this commit and attach binaries to a GitHub release?"
    fields:
      - text: "Version"
        hint: "The git tag to create e.g. v2.1.0"
        key: "version"
    branches:
      - master

  - name: ":octocat: :rocket:"
    command: ".buildkite/steps/github-release.sh"
    branches:
      - master
    agents:
      queue: "on-demand"
      task-definition: github-publish-buildkite-elastic-stack-releaser
