steps:
  - wait

  - label: ":linux: x86_64"
    plugins:
      docker-compose#v3.7.0:
        config: .buildkite/docker-compose.yml
        run: agent
        mount-buildkite-agent: true
    command: .buildkite/steps/build-binary.sh
    env:
      GOOS: linux
      GOARCH: amd64

  - label: ":linux: arm64"
    plugins:
      docker-compose#v3.7.0:
        config: .buildkite/docker-compose.yml
        run: agent
        mount-buildkite-agent: true
    command: .buildkite/steps/build-binary.sh
    env:
      GOOS: linux
      GOARCH: arm64

  - label: ":windows: x86_64"
    plugins:
      docker-compose#v3.7.0:
        config: .buildkite/docker-compose.yml
        run: agent
        mount-buildkite-agent: true
    command: .buildkite/steps/build-binary.sh
    env:
      GOOS: windows
      GOARCH: amd64

  # Requires golang 1.17 with support for windows/arm64
  # https://tip.golang.org/doc/go1.17
  # https://github.com/golang/go/issues/36439
  # - label: ":windows: arm64"
  #   plugins:
  #     docker-compose#v3.7.0:
  #       config: .buildkite/docker-compose.yml
  #       run: agent
  #       mount-buildkite-agent: true
  #   command: .buildkite/steps/build-binary.sh
  #   env:
  #     GOOS: windows
  #     GOARCH: arm64

  - label: ":mac: x86_64"
    plugins:
      docker-compose#v3.7.0:
        config: .buildkite/docker-compose.yml
        run: agent
        mount-buildkite-agent: true
    command: .buildkite/steps/build-binary.sh
    env:
      GOOS: darwin
      GOARCH: amd64

  - label: ":mac: arm64"
    plugins:
      docker-compose#v3.7.0:
        config: .buildkite/docker-compose.yml
        run: agent
        mount-buildkite-agent: true
    command: .buildkite/steps/build-binary.sh
    env:
      GOOS: darwin
      GOARCH: arm64

  - wait

  - label: ":go: Unit Tests"
    plugins:
      docker-compose#v5.10.0:
        config: .buildkite/docker-compose.yml
        run: tests
    command: .buildkite/steps/tests.sh

  - label: "㊙️ git-credentials test"
    command: .buildkite/test_credentials.sh
    plugins:
      - aws-assume-role-with-web-identity#v1.4.0:
          role-arn: arn:aws:iam::172840064832:role/pipeline-buildkite-aws-stack-elastic-ci-stack-s3-secrets-hooks
          session-tags:
            - organization_slug
            - organization_id
            - pipeline_slug

  - wait

  - block: ":git: tag?"
    prompt: "Tag this commit and attach binaries to a GitHub release?"
    fields:
      - text: "Version"
        hint: "The git tag to create e.g. v2.1.0"
        key: "version"
    branches:
      - main

  - name: ":octocat: :rocket:"
    command: ".buildkite/steps/github-release.sh"
    branches:
      - main
    plugins:
      - aws-assume-role-with-web-identity#v1.4.0:
          role-arn: arn:aws:iam::172840064832:role/pipeline-elastic-ci-stack-s3-secrets-hooks-main
          session-tags:
            - organization_slug
            - organization_id
            - pipeline_slug
            - build_branch
      - aws-ssm#v1.0.0:
          parameters:
            GITHUB_RELEASE_ACCESS_TOKEN: /pipelines/buildkite-aws-stack/elastic-ci-stack-s3-secrets-hooks/GITHUB_RELEASE_ACCESS_TOKEN
      - docker-compose#v3.7.0:
          config: .buildkite/docker-compose.yml
          run: release
          mount-buildkite-agent: true
          env:
            - GITHUB_RELEASE_ACCESS_TOKEN

  - label: ":shell: Tests"
    plugins:
      - plugin-tester#v1.2.0:
          folders:
            - tests

  - label: ":sparkles: Lint"
    plugins:
      - plugin-linter#v3.3.0:
          id: elastic-ci-stack-s3-secrets-hooks

  - label: ":shell: Shellcheck"
    plugins:
      - shellcheck#v1.4.0:
          files:
            - hooks/**