#!/bin/bash
set -e -o pipefail -u

basedir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd .. && pwd )"
credhelper="$basedir/git-credential-s3-secrets"

# s3secrets-helper must be in PATH
envscript="$(
  BUILDKITE_PLUGIN_S3_SECRETS_CREDHELPER="$credhelper" \
    s3secrets-helper
)"

env_before="$(env | sort)"
echo "Evaluating ${#envscript} bytes of env"
set -o allexport
eval "$envscript"
set +o allexport

if [[ "${BUILDKITE_PLUGIN_S3_SECRETS_DUMP_ENV:-}" =~ ^(true|1)$ ]] ; then
  echo "~~~ Environment variables that were set" >&2;
  comm -13 <(echo "$env_before") <(env | sort) || true
fi
